-- ELBAYAA Store - Supabase database setup
create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price numeric(12,2) not null default 0,
  old_price numeric(12,2),
  image text,
  category text not null default '',
  rating numeric(2,1) not null default 0,
  description text not null default '',
  stock integer not null default 0,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null,
  payment_method text not null default 'الدفع عند الاستلام',
  total numeric(12,2) not null default 0,
  items jsonb not null default '[]'::jsonb,
  status text not null default 'جديد',
  created_at timestamptz not null default now()
);

create table if not exists public.admin_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.admin_profiles enable row level security;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_profiles
    where user_id = auth.uid() and is_admin = true
  );
$$;

-- Products: everyone can see active products; admins can manage all products.
drop policy if exists "public read active products" on public.products;
create policy "public read active products" on public.products
for select using (active = true or public.is_admin());

drop policy if exists "admins insert products" on public.products;
create policy "admins insert products" on public.products
for insert with check (public.is_admin());

drop policy if exists "admins update products" on public.products;
create policy "admins update products" on public.products
for update using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admins delete products" on public.products;
create policy "admins delete products" on public.products
for delete using (public.is_admin());

-- Customers can submit an order anonymously; only admins can read/change orders.
drop policy if exists "customers create orders" on public.orders;
create policy "customers create orders" on public.orders
for insert with check (true);

drop policy if exists "admins read orders" on public.orders;
create policy "admins read orders" on public.orders
for select using (public.is_admin());

drop policy if exists "admins update orders" on public.orders;
create policy "admins update orders" on public.orders
for update using (public.is_admin()) with check (public.is_admin());

-- Admins may read their own admin row.
drop policy if exists "admins read own profile" on public.admin_profiles;
create policy "admins read own profile" on public.admin_profiles
for select using (user_id = auth.uid());

-- Seed products only if the table is empty.
insert into public.products (name, price, old_price, image, category, rating, description, stock, featured)
select * from (values
 ('سماعة بلوتوث لاسلكية',199,249,'🎧','سماعات',4.8,'سماعة بلوتوث لاسلكية بجودة صوت ممتازة.',25,true),
 ('كابل تايب سي لايتنينج',99,149,'🔌','كابلات',4.9,'كابل عملي للشحن ونقل البيانات.',40,true),
 ('كفر حماية ماج سيف',89,129,'📱','كفرات وجرابات',4.7,'كفر حماية أنيق ومتوافق مع MagSafe.',30,true),
 ('شاحن سريع 20W',149,199,'🔋','شواحن',4.8,'شاحن سريع بقدرة 20W للاستخدام اليومي.',20,true)
) as seed(name,price,old_price,image,category,rating,description,stock,featured)
where not exists (select 1 from public.products);
